let drinks = [
    "Tropical Thunder",
    "Coriander and Coconut Virgin Mojito",
    "Cool as Cucumber",
    "Bollywood Smash",
    " Queens Necklace ",
    "Bombay-Champeach Bellini ",
    " Lychee Bellini ",
    " Aperol Spiritz ",
    "Snow's Negroni ",
    "Pimmonade",
    " Vodka Bitters",
    " Tamarind Margarita ",
    " Goan Martini ",
    " Mango Mojito ",
    " Pomegranate Martini",
    " Spicy Baby",
    " Classic Margarita ",
    " Classic Martini ",
    " Classic mojito",
    "Long Island Iced Tea",
    "Cosmopolitan",
    " Espresso Martini",
    " Old Fashioned",
    "Dark and Stormy",
    " Cuba libre",
    " Amaretto Sours ",
];
